version: '2'
services:
  neiistalive:
    build: .
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/src
      - /src/node_modules
    ports:
      - "3000:80"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: "mongodb"
    environment:
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null # --quiet